# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ma'ayan Lab Dokku Server
author: Ma'ayan Lab
logo: _assets/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: dokku.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/maayanlab/dokku
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  extra_navbar: ""

sphinx:
  extra_extensions:
    - sphinx.ext.extlinks
  config:
    # all files in _assets will be placed in the root, including the downloads directory
    html_extra_path: [_assets]
    # this sets up a sphinx role: {downloads}`my-file-in-downloads`
    extlinks:
      downloads: ['/downloads/%s', '%s']
